// test/page.test.js — SITE BUILD (easymahjongsolitaire.com).
//
// The portal build was one self-contained index.html with its CSS inline
// and the CrazyGames SDK in the head. On this site the page has to obey
// the site's own rules instead, and every one of them is the kind that
// breaks silently: a style="" added during a later fix is refused by the
// Content-Security-Policy and the game just looks wrong; a game_start
// moved to boot double-counts every visit; the top bar's markup is
// generated by tools/sync-games.mjs and a hand-edit can drop it.
//
// Nothing here tests the GAME — the other eleven suites do that, and none
// of them changed for this port. This pins the port itself.
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test, assertEqual, assertTrue } from "./harness.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const URL = "https://easymahjongsolitaire.com/dots-and-boxes/";
const html = readFileSync(path.join(root, "index.html"), "utf8");
const css = readFileSync(path.join(root, "style.css"), "utf8");
const main = readFileSync(path.join(root, "src", "main.js"), "utf8");
const noComments = html.replace(/<!--[\s\S]*?-->/g, "");
const srcFiles = ["src/main.js", "src/core/ads.js", "src/core/audio.js", "src/core/grid.js",
  "src/core/input.js", "src/core/storage.js", "src/core/turn.js", "src/game/achievements.js",
  "src/game/ai.js", "src/game/chains.js", "src/game/daily.js", "src/game/position.js",
  "src/game/quickstart.js", "src/game/render.js", "src/game/rules.js", "src/game/theme.js"]
  .map((f) => [f, readFileSync(path.join(root, f), "utf8")]);

// --- the CSP: `script-src 'self' + googletagmanager; style-src 'self'` ----

test("no inline <style>: the stylesheet is a file the CSP will serve", () => {
  assertTrue(!/<style[\s>]/.test(noComments), "index.html has no <style> block");
  assertTrue(/<link rel="stylesheet" href="\.\/style\.css" \/>/.test(html), "it links ./style.css");
});

test('no style="" attribute anywhere in the page', () => {
  assertTrue(!/\sstyle="/.test(noComments), "index.html");
});

test("no inline <script> other than JSON-LD", () => {
  const inline = [...noComments.matchAll(/<script(?![^>]*\ssrc=)([^>]*)>/g)]
    .filter((m) => !/type="application\/ld\+json"/.test(m[1]));
  assertEqual(inline.length, 0, "inline scripts");
});

test("no JS writes a style attribute — el.style.x is CSSOM and fine, a string is not", () => {
  for (const [name, text] of srcFiles) {
    assertTrue(!/setAttribute\(\s*["']style/.test(text), `${name} never setAttribute("style", …)`);
    assertTrue(!/style="/.test(text), `${name} has no style="" in a string (innerHTML included)`);
  }
});

test("nothing loads from a host the CSP does not allow", () => {
  const hosts = [
    ...noComments.matchAll(/<script[^>]*\ssrc="https?:\/\/([^/"]+)/g),
    ...noComments.matchAll(/<link[^>]*rel="stylesheet"[^>]*href="https?:\/\/([^/"]+)/g),
  ].map((m) => m[1]);
  for (const h of hosts) {
    assertTrue(["www.googletagmanager.com", "fonts.googleapis.com"].includes(h), `allowed host: ${h}`);
  }
  assertTrue(!/sdk\.crazygames\.com/.test(noComments), "the CrazyGames SDK tag is gone");
});

// --- the head block -------------------------------------------------------

test("the <title> ends with the brand and the head points at this page", () => {
  assertTrue(/<title>[^<]*\| Easy Classics<\/title>/.test(html), "title ends with | Easy Classics");
  assertTrue(html.includes(`<link rel="canonical" href="${URL}">`), "canonical");
  assertTrue(html.includes(`<meta property="og:url" content="${URL}">`), "og:url");
  assertTrue(html.includes(`og-image.png`), "og:image");
  assertTrue(/<meta name="description" content=".{80,}?">/.test(html), "a real description");
  assertTrue(/href="data:image\/svg\+xml,/.test(html), "an inline-SVG favicon");
  assertTrue(html.includes('src="/ga-init.js"') && html.includes("gtag/js?id=G-CPBFW58QG6"), "GA4 via /ga-init.js");
  assertTrue(html.includes('src="/_vercel/insights/script.js"'), "Vercel insights");
});

test("the JSON-LD parses and describes this URL", () => {
  const m = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
  assertTrue(!!m, "there is JSON-LD");
  const data = JSON.parse(m[1]);
  assertEqual(data["@type"], "WebApplication", "@type");
  assertEqual(data.url, URL, "url");
  assertEqual(data.isAccessibleForFree, true, "free");
});

// --- the top bar (DESIGN.md "Site navigation") ----------------------------

test("the page carries the generated bar and loads the shared /nav.js", () => {
  assertTrue(html.includes("<!-- games:nav -->") && html.includes("<!-- /games:nav -->"),
    "the fence tools/sync-games.mjs writes into");
  assertTrue(/<script type="module" src="\/nav\.js"><\/script>/.test(html), "loads /nav.js");
  assertTrue(html.includes('id="link-crossgame-home"') && html.includes('class="nav-brand" href="/"'),
    "the wordmark is the home link, id and all");
  assertTrue(!/class="site-header"/.test(noComments), "no green banner left");
});

test("exactly one <h1>, and it is <main>'s first child", () => {
  assertEqual([...noComments.matchAll(/<h1[\s>]/g)].length, 1, "one h1");
  const mainAt = noComments.indexOf("<main");
  assertTrue(mainAt > -1, "there is a <main>");
  const after = noComments.slice(noComments.indexOf(">", mainAt) + 1).trim();
  assertTrue(after.startsWith('<h1 class="game-title">'), `first in <main>, got ${after.slice(0, 40)}`);
});

test("the bar hides during play, and the game remeasures in the same frame", () => {
  assertTrue(/body\[data-nav="hidden"\] \.site-nav \{\s*display: none;?\s*\}/.test(css),
    "style.css hides the bar on the body attribute");
  const fn = main.slice(main.indexOf("function syncNav()"), main.indexOf("function openGamesPanel"));
  assertTrue(fn.includes('document.body.dataset.nav = want'), "syncNav sets the attribute");
  assertTrue(fn.includes("resizeCanvas()"), "and remeasures the canvas itself");
  // Called from the END of updateHud(), after the hidden/disabled toggles
  // it has to measure against — see the comment there.
  const hud = main.slice(main.indexOf("function updateHud()"), main.indexOf("function turnLabelText"));
  assertTrue(/syncNav\(\);\s*\}\s*$/.test(hud), "updateHud() ends with syncNav()");
});

test("the panel is reachable while the bar is hidden", () => {
  assertTrue(/id="games-btn"[^>]*>Games</.test(html.replace(/\n\s+/g, " ")),
    "a word-labelled Games button in the game's own top row");
  assertTrue(main.includes('placement: "game_menu"'), "and it reports the game_menu placement");
});

test("the panel is above this game's modals and below its toasts", () => {
  const z = (sel) => Number((css.match(new RegExp(sel + "[^}]*z-index: (\\d+)"))||[])[1]);
  const panel = z("\\.nav-panel \\{");
  assertTrue(panel > z("\\.modal-overlay \\{"), `panel ${panel} over the modals`);
  assertTrue(panel < z("#achievement-toast-container \\{"), `panel ${panel} under the toasts`);
});

// --- analytics ------------------------------------------------------------

test("every event carries this page's game_name", () => {
  assertTrue(main.includes('const GA_NAME = "dots_and_boxes"'), "game_name is dots_and_boxes");
  assertTrue(main.includes("typeof window.gtag === \"function\""), "gtag is checked before it is called");
});

test("game_start fires at the player's own entry, never at boot", () => {
  assertEqual([...main.matchAll(/trackEvent\("game_start"/g)].length, 2,
    "twice: startGame() and startDailyChallenge()");
  for (const fn of ["startGame", "startDailyChallenge"]) {
    const body = main.slice(main.indexOf(`function ${fn}()`));
    assertTrue(body.slice(0, body.indexOf("\n}\n")).includes('trackEvent("game_start"'), `${fn} reports it`);
  }
  // The page boots onto a setup screen with a dead board preview behind
  // the Play button. Nothing at module scope may start a game.
  assertTrue(!/^startGame\(\);$/m.test(main), "boot does not call startGame()");
  assertTrue(/^enterSetup\(\);$/m.test(main), "boot lands on enterSetup()");
});

test("game_win fires once, only when the player actually won", () => {
  assertEqual([...main.matchAll(/trackEvent\("game_win"/g)].length, 1, "one call site");
  const at = main.indexOf('trackEvent("game_win"');
  const fn = main.lastIndexOf("function playMoveSound", at);
  assertTrue(fn > -1 && main.slice(fn, at).includes("result.gameOver"),
    "inside playMoveSound()'s gameOver branch — the one move that ends a game");
  assertTrue(main.includes("const humanWon = hasAiOpponent() ? state.winner === 0 : state.winner !== \"draw\""),
    "a draw is not a win, and neither is the AI taking the board");
});

test("the cross-game links report themselves (the bar's wordmark included)", () => {
  assertTrue(main.includes("function wireCrossGameLinks()"), "copied from the site's game.js");
  assertTrue(main.includes('a[data-crossgame-to]'), "wires the links, does not list the games");
  assertTrue(/^wireCrossGameLinks\(\);$/m.test(main), "and is actually called");
});
