// game/stages.js
// The four-ball campaign: twenty-one problems, each one built backwards
// from a shot that works and each one carrying that shot in the file.
//
// WHY A CAMPAIGN AND NOT A 30-POINT MATCH
// StoneFlick's kickoff note settled this for the series: a web player
// gives a game about forty seconds to justify itself, and a four-ball
// match against an AI does not produce a moment worth staying for inside
// forty seconds — it produces a beginner missing, handing over the table,
// and watching. A placed problem does: the balls are already in a shape
// where a point EXISTS, the player can see that it exists, and the only
// question is whether they can play it. That is a puzzle, and a puzzle is
// something a stranger will try twice.
//
// ALL PLAYER-FACING TEXT IN THIS FILE IS ENGLISH, and that is a product
// rule, not a translation choice: the audience is the English-speaking
// web portal. Four-ball is close to unknown outside Korea and Japan, so
// these hints are also the only rulebook most players will ever read —
// they have to teach "follow", "draw", "thin" and "side" in the words an
// English player would look those up under.
//
// Positions are in table metres (2.84 x 1.42), origin at the head-left
// corner of the cloth.
//
// DIFFICULTY IS DISTANCE, AND THESE PLACEMENTS WERE MEASURED
// The first draft of this file was placed by eye, and tools/shot-search.mjs
// then measured it: every stage had a scoring window between 0.1% and 0.6%
// of sampled shots. Stage 1 was the worst and looked like the easiest —
// three balls in a dead straight line, where the first red leaves along
// the very line the cue ball is on and screens the second one for the
// whole shot. A position can look obvious and have no answer.
//
// So these are built backwards from a shot that works: play a chosen
// stroke, trace where the cue ball goes, and put the reds on that path.
// Every stage below therefore has at least one solution BY CONSTRUCTION,
// and it is recorded in `solution` — which makes the campaign
// self-verifying, since test/stages.test.js replays it. Change a friction
// constant and the stages fail loudly instead of quietly becoming
// impossible.
//
// `aimWindow` is the measured degrees of aim either side of that solution
// that still score, and it is the honest difficulty number. It is mostly
// set by DISTANCE: aiming off by d moves the contact point on the first
// red by (distance to it) x d, which changes how full the hit is, which
// swings the cue ball's departure by several times d, which is multiplied
// again by the distance to the second red. So a tight cluster forgives ten
// degrees and a spread-out table forgives one. That is why most stages
// here are built close together — which is also what a real four-ball
// table looks like after a few shots.
//
// `covers` AND `requires`: THE PART THAT IS NEW
// Seven stages could be placed by hand and eyeballed for variety.
// Twenty-one cannot, and "variety" was never the right target anyway —
// the target is COVERAGE. Every one of these is generated by a named case
// in tools/stage-lab.mjs (`covers`), and the set is chosen so that between
// them they exercise every stroke the physics implements (stun, follow,
// draw, side), every route (direct, one rail before, one rail between,
// two rails), every awkward position (cue ball on a cushion, in a corner,
// reds frozen to each other, reds frozen to a rail, the yellow screening
// the line, both contacts feathered), and both ends of the speed and
// distance ranges. When a physics constant moves, the failure lands in
// whichever corner of the model it broke rather than in "some stage".
//
// `requires` is the stronger claim and it is CHECKED, not asserted. A
// stage that says "draw" is a stage where a stun or follow shot on the
// same line does not score; one that says "cushionFirst" is one where no
// direct shot scores anywhere on the table. test/stages.test.js re-runs
// those searches, so a stage cannot quietly stop teaching its lesson.
//
// That check earned its place immediately. The previous "Rail First" —
// hint: "Every direct line is the wrong one" — turned out to have FOUR
// direct shots that score. It had been a rail stage in name only since it
// was built, and nothing in the old suite could see it. It is replaced
// here by a generated one that passes.
//
// THE CUSHION STAGES NEEDED THE CONTROL FIXED FIRST
// The first attempt at a rail stage came out at a quarter of a degree of
// aim window and was thrown away: no drag can hit that. It took splitting
// aim from shooting — a nudge that turns the shot a fifth of a degree at
// a time — before three degrees was worth building, and then one more
// thing in the generator. A red placed just past a cushion sits 4cm from
// it, the cue ball leaves that contact travelling almost parallel to the
// rail, and it skims along it for the rest of the shot with nowhere legal
// to put the second red. Pushing the FIRST red out to 30cm from every
// rail is what gives the second leg a table to happen on.

const W = 1.27;
const L = 2.54;

/** @typedef {{id:string, name:string, hint:string, par:number,
 *             covers:string, requires:string, aimWindow:number,
 *             solution:{deg:number, speed:number, tip:number, side:number},
 *             balls:{cue:[number,number], yellow:[number,number],
 *                    red1:[number,number], red2:[number,number]}}} Stage */

/**
 * @type {Stage[]}
 * Ordered by how much aim they forgive, not by stroke — the first thing a
 * new player needs is a point on the board, not a curriculum. The
 * curriculum happens anyway, because the forgiving positions are the
 * close ones and the close ones are where the simple strokes live.
 *
 * `solution` is one shot that scores: direction in degrees (table space,
 * +x along the table), cue speed in m/s, and tip offsets in ball radii —
 * `tip` positive for follow and negative for draw, `side` for english.
 */
export const STAGES = [
  {
    id: "s1",
    name: "Stage 1",
    covers: "cluster",
    requires: "any",
    par: 1,
    aimWindow: 12,
    solution: { deg: -100.503, speed: 1.822, tip: 0.217, side: 0 },
    balls: { cue: [1.708,0.725], red1: [1.661,0.578], red2: [1.727,0.497], yellow: [1.336,0.22] },
  },
  {
    id: "s2",
    name: "Stage 2",
    covers: "tightCorner",
    requires: "any",
    par: 1,
    aimWindow: 9.5,
    solution: { deg: 89.752, speed: 1.206, tip: 0.341, side: 0.3 },
    balls: { cue: [2.404,0.088], red1: [2.378,0.204], red2: [2.392,0.326], yellow: [0.276,0.716] },
  },
  {
    id: "s3",
    name: "Stage 3",
    covers: "cluster",
    requires: "any",
    par: 1,
    aimWindow: 11.75,
    solution: { deg: -31.877, speed: 1.256, tip: 0.005, side: 0 },
    balls: { cue: [1.381,0.948], red1: [1.63,0.838], red2: [1.699,0.655], yellow: [0.22,1.035] },
  },
  {
    id: "s4",
    name: "Stage 4",
    covers: "tightCorner",
    requires: "any",
    par: 1,
    aimWindow: 9.5,
    solution: { deg: -155.869, speed: 1.727, tip: 0.265, side: 0 },
    balls: { cue: [2.469,1.193], red1: [2.282,1.069], red2: [2.226,1.161], yellow: [1.705,0.748] },
  },
  {
    id: "s5",
    name: "Stage 5",
    covers: "cluster",
    requires: "any",
    par: 1,
    aimWindow: 11.5,
    solution: { deg: -163.223, speed: 1.762, tip: 0.344, side: 0 },
    balls: { cue: [0.69,0.36], red1: [0.41,0.314], red2: [0.355,0.181], yellow: [0.769,1.05] },
  },
  {
    id: "s6",
    name: "Stage 6",
    covers: "tightCorner",
    requires: "any",
    par: 1,
    aimWindow: 9.5,
    solution: { deg: -119.396, speed: 2.2, tip: 0.4, side: 0 },
    balls: { cue: [2.475,0.136], red1: [2.396,0.135], red2: [2.263,0.142], yellow: [0.22,0.893] },
  },
  {
    id: "s7",
    name: "Stage 7",
    covers: "cluster",
    requires: "any",
    par: 1,
    aimWindow: 11,
    solution: { deg: -22.936, speed: 1.402, tip: 0.276, side: 0 },
    balls: { cue: [0.749,0.564], red1: [0.892,0.486], red2: [0.978,0.517], yellow: [0.287,1.05] },
  },
  {
    id: "s8",
    name: "Stage 8",
    covers: "tightCorner",
    requires: "any",
    par: 1,
    aimWindow: 9.25,
    solution: { deg: -15.44, speed: 1.96, tip: 0.049, side: 0 },
    balls: { cue: [0.13,1.171], red1: [0.258,1.152], red2: [0.315,0.977], yellow: [1.363,1.017] },
  },
  {
    id: "s9",
    name: "Stage 9",
    covers: "tightCorner",
    requires: "any",
    par: 1,
    aimWindow: 9.25,
    solution: { deg: 138.638, speed: 1.604, tip: 0.279, side: 0 },
    balls: { cue: [2.425,1.203], red1: [2.191,1.135], red2: [2.164,0.988], yellow: [1.738,0.99] },
  },
  {
    id: "s10",
    name: "Stage 10",
    covers: "stun",
    requires: "any",
    par: 2,
    aimWindow: 6.5,
    solution: { deg: -171.684, speed: 1.978, tip: 0, side: 0 },
    balls: { cue: [1.351,0.395], red1: [0.999,0.38], red2: [0.945,0.171], yellow: [0.947,1.05] },
  },
  {
    id: "s11",
    name: "Stage 11",
    covers: "openTable",
    requires: "any",
    par: 2,
    aimWindow: 7.75,
    solution: { deg: -159.071, speed: 2.131, tip: 0.081, side: 0 },
    balls: { cue: [1.822,0.776], red1: [1.587,0.649], red2: [0.68,0.98], yellow: [1.078,0.605] },
  },
  {
    id: "s12",
    name: "Stage 12",
    covers: "redsApart",
    requires: "any",
    par: 2,
    aimWindow: 6.5,
    solution: { deg: -60.186, speed: 3.285, tip: 0.259, side: 0.187 },
    balls: { cue: [0.475,0.522], red1: [0.607,0.229], red2: [1.863,0.214], yellow: [0.22,0.794] },
  },
  {
    id: "s13",
    name: "Stage 13",
    covers: "frozenPair",
    requires: "any",
    par: 2,
    aimWindow: 6.5,
    solution: { deg: 23.108, speed: 1.965, tip: 0.051, side: 0 },
    balls: { cue: [2.082,0.405], red1: [2.477,0.605], red2: [2.448,0.512], yellow: [1.804,0.22] },
  },
  {
    id: "s14",
    name: "Stage 14",
    covers: "openTable",
    requires: "any",
    par: 2,
    aimWindow: 6.25,
    solution: { deg: 163.12, speed: 2.476, tip: 0.172, side: 0.3 },
    balls: { cue: [2.169,0.401], red1: [1.902,0.516], red2: [0.216,0.153], yellow: [0.741,0.724] },
  },
  {
    id: "s15",
    name: "Stage 15",
    covers: "stun",
    requires: "any",
    par: 2,
    aimWindow: 6.25,
    solution: { deg: 35.355, speed: 2.04, tip: 0, side: 0 },
    balls: { cue: [0.738,0.415], red1: [1.037,0.586], red2: [1.011,0.865], yellow: [0.585,0.698] },
  },
  {
    id: "s16",
    name: "Stage 16",
    covers: "cueOnRail",
    requires: "any",
    par: 2,
    aimWindow: 6.25,
    solution: { deg: -103.07, speed: 3, tip: 0.4, side: 0 },
    balls: { cue: [1.736,0.058], red1: [1.626,0.419], red2: [1.854,0.649], yellow: [1.153,1.05] },
  },
  {
    id: "s17",
    name: "Stage 17",
    covers: "openTable",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 130.613, speed: 3.075, tip: 0.385, side: 0 },
    balls: { cue: [1.681,0.523], red1: [1.497,0.795], red2: [0.261,1.114], yellow: [1.374,0.453] },
  },
  {
    id: "s18",
    name: "Stage 18",
    covers: "stun",
    requires: "any",
    par: 2,
    aimWindow: 6.25,
    solution: { deg: 47.346, speed: 1.761, tip: 0, side: 0 },
    balls: { cue: [1.521,0.772], red1: [1.777,1.105], red2: [1.958,1.062], yellow: [0.224,0.782] },
  },
  {
    id: "s19",
    name: "Stage 19",
    covers: "frozenPair",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 100.253, speed: 2.529, tip: 0.152, side: 0 },
    balls: { cue: [1.777,0.932], red1: [1.741,1.143], red2: [1.813,1.063], yellow: [1.147,0.22] },
  },
  {
    id: "s20",
    name: "Stage 20",
    covers: "cueOnRail",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: -24.638, speed: 2.462, tip: 0.037, side: 0 },
    balls: { cue: [0.955,1.187], red1: [1.33,1.053], red2: [1.388,0.739], yellow: [1.733,1.05] },
  },
  {
    id: "s21",
    name: "Stage 21",
    covers: "stun",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 121.425, speed: 1.585, tip: -0.4, side: -0.3 },
    balls: { cue: [0.859,0.827], red1: [0.826,1.197], red2: [0.625,1.15], yellow: [1.941,0.851] },
  },
  {
    id: "s22",
    name: "Stage 22",
    covers: "frozenPair",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: -152.201, speed: 1.883, tip: -0.163, side: 0.3 },
    balls: { cue: [0.909,0.961], red1: [0.393,0.646], red2: [0.339,0.696], yellow: [1.913,1.05] },
  },
  {
    id: "s23",
    name: "Stage 23",
    covers: "softTouch",
    requires: "soft",
    par: 3,
    aimWindow: 5,
    solution: { deg: 15.373, speed: 1.497, tip: 0.047, side: 0 },
    balls: { cue: [1.378,0.475], red1: [1.668,0.521], red2: [2.381,1.118], yellow: [1.102,0.22] },
  },
  {
    id: "s24",
    name: "Stage 24",
    covers: "cueInCorner",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: -142.618, speed: 1.732, tip: 0.227, side: 0 },
    balls: { cue: [2.47,0.1], red1: [2.26,0.155], red2: [1.9,0.074], yellow: [2.099,0.22] },
  },
  {
    id: "s25",
    name: "Stage 25",
    covers: "stun",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 11.739, speed: 1.235, tip: 0, side: 0 },
    balls: { cue: [1.799,0.559], red1: [2.14,0.673], red2: [2.349,0.5], yellow: [0.889,0.252] },
  },
  {
    id: "s26",
    name: "Stage 26",
    covers: "frozenPair",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 2.111, speed: 2.009, tip: 0.4, side: 0 },
    balls: { cue: [0.503,0.577], red1: [0.905,0.622], red2: [0.942,0.504], yellow: [2.32,0.64] },
  },
  {
    id: "s27",
    name: "Stage 27",
    covers: "cueInCorner",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 52.645, speed: 1.749, tip: -0.069, side: 0 },
    balls: { cue: [0.127,0.145], red1: [0.386,0.538], red2: [0.532,0.542], yellow: [0.73,0.74] },
  },
  {
    id: "s28",
    name: "Stage 28",
    covers: "softTouch",
    requires: "soft",
    par: 3,
    aimWindow: 5,
    solution: { deg: -165.051, speed: 1.358, tip: 0.022, side: 0 },
    balls: { cue: [1.734,0.843], red1: [1.456,0.805], red2: [0.611,0.119], yellow: [2.03,1.042] },
  },
  {
    id: "s29",
    name: "Stage 29",
    covers: "cueOnRail",
    requires: "any",
    par: 2,
    aimWindow: 5.75,
    solution: { deg: 27.481, speed: 3, tip: 0.342, side: 0 },
    balls: { cue: [1.466,1.208], red1: [1.744,1.105], red2: [2.483,1.16], yellow: [1.492,1.05] },
  },
  {
    id: "s30",
    name: "Stage 30",
    covers: "frozenPair",
    requires: "any",
    par: 2,
    aimWindow: 5.5,
    solution: { deg: -86.364, speed: 2.923, tip: -0.4, side: 0 },
    balls: { cue: [1.684,0.947], red1: [1.601,0.608], red2: [1.737,0.565], yellow: [1.238,0.674] },
  },
  {
    id: "s31",
    name: "Stage 31",
    covers: "cueInCorner",
    requires: "any",
    par: 2,
    aimWindow: 6,
    solution: { deg: 5.699, speed: 1.723, tip: 0.275, side: 0 },
    balls: { cue: [0.077,1.138], red1: [0.398,1.127], red2: [0.646,1.117], yellow: [2.107,0.22] },
  },
  {
    id: "s32",
    name: "Stage 32",
    covers: "cueOnRail",
    requires: "any",
    par: 2,
    aimWindow: 5.75,
    solution: { deg: -91.702, speed: 3, tip: -0.119, side: 0.3 },
    balls: { cue: [1.853,1.201], red1: [1.811,0.881], red2: [2.034,0.822], yellow: [0.854,0.547] },
  },
  {
    id: "s33",
    name: "Stage 33",
    covers: "openTable",
    requires: "any",
    par: 3,
    aimWindow: 4.75,
    solution: { deg: -22.831, speed: 2.039, tip: 0.172, side: 0 },
    balls: { cue: [0.983,1.043], red1: [1.296,0.869], red2: [2.361,1.06], yellow: [0.659,0.957] },
  },
  {
    id: "s34",
    name: "Stage 34",
    covers: "followOnly",
    requires: "follow",
    par: 2,
    aimWindow: 5.5,
    solution: { deg: 0.006, speed: 1.895, tip: 0.424, side: 0 },
    balls: { cue: [1.935,0.455], red1: [2.018,0.446], red2: [2.375,0.602], yellow: [2.32,0.945] },
  },
  {
    id: "s35",
    name: "Stage 35",
    covers: "cueInCorner",
    requires: "any",
    par: 2,
    aimWindow: 5.75,
    solution: { deg: 24.767, speed: 1.594, tip: 0.234, side: 0.3 },
    balls: { cue: [0.081,1.202], red1: [0.522,1.172], red2: [0.615,0.988], yellow: [1.159,1.05] },
  },
  {
    id: "s36",
    name: "Stage 36",
    covers: "softTouch",
    requires: "soft",
    par: 3,
    aimWindow: 5.25,
    solution: { deg: 17.94, speed: 1.376, tip: -0.023, side: 0 },
    balls: { cue: [0.996,0.787], red1: [1.263,0.841], red2: [1.592,1.109], yellow: [0.351,0.22] },
  },
  {
    id: "s37",
    name: "Stage 37",
    covers: "followOnly",
    requires: "follow",
    par: 2,
    aimWindow: 5.5,
    solution: { deg: 20.166, speed: 1.538, tip: 0.433, side: 0 },
    balls: { cue: [0.758,0.964], red1: [0.882,1.004], red2: [1.292,1.195], yellow: [1.828,0.646] },
  },
  {
    id: "s38",
    name: "Stage 38",
    covers: "softTouch",
    requires: "soft",
    par: 3,
    aimWindow: 5.25,
    solution: { deg: 22.932, speed: 1.395, tip: 0.029, side: 0 },
    balls: { cue: [0.515,0.564], red1: [0.787,0.64], red2: [1.251,1.112], yellow: [0.22,0.22] },
  },
  {
    id: "s39",
    name: "Stage 39",
    covers: "followOnly",
    requires: "follow",
    par: 3,
    aimWindow: 5.25,
    solution: { deg: -117.082, speed: 2.2, tip: 0.432, side: 0 },
    balls: { cue: [0.919,0.363], red1: [0.874,0.263], red2: [0.659,0.081], yellow: [2.067,0.391] },
  },
  {
    id: "s40",
    name: "Stage 40",
    covers: "openTable",
    requires: "any",
    par: 3,
    aimWindow: 4.75,
    solution: { deg: -124.477, speed: 3.167, tip: 0.079, side: 0 },
    balls: { cue: [2.375,0.778], red1: [2.222,0.494], red2: [1.252,0.328], yellow: [0.22,0.22] },
  },
  {
    id: "s41",
    name: "Stage 41",
    covers: "followOnly",
    requires: "follow",
    par: 3,
    aimWindow: 5.25,
    solution: { deg: 109.839, speed: 1.667, tip: 0.367, side: 0 },
    balls: { cue: [1.563,0.505], red1: [1.53,0.582], red2: [1.492,0.87], yellow: [1.923,1.05] },
  },
  {
    id: "s42",
    name: "Stage 42",
    covers: "englishOnly",
    requires: "english",
    par: 3,
    aimWindow: 4.75,
    solution: { deg: 104.116, speed: 1.4, tip: 0, side: 0.3 },
    balls: { cue: [1.916,1.055], red1: [1.622,0.812], red2: [1.441,0.792], yellow: [2.02,0.528] },
  },
  {
    id: "s43",
    name: "Stage 43",
    covers: "redsApart",
    requires: "any",
    par: 3,
    aimWindow: 4.5,
    solution: { deg: -69.027, speed: 3.144, tip: 0.367, side: 0.181 },
    balls: { cue: [0.662,1.032], red1: [0.758,0.692], red2: [2.204,0.208], yellow: [0.297,0.801] },
  },
  {
    id: "s44",
    name: "Stage 44",
    covers: "followOnly",
    requires: "follow",
    par: 3,
    aimWindow: 5,
    solution: { deg: 42.626, speed: 1.606, tip: 0.411, side: 0 },
    balls: { cue: [1.668,0.864], red1: [1.743,0.942], red2: [2.301,1.187], yellow: [0.508,1.05] },
  },
  {
    id: "s45",
    name: "Stage 45",
    covers: "englishOnly",
    requires: "english",
    par: 3,
    aimWindow: 4.75,
    solution: { deg: 96.508, speed: 1.641, tip: 0.112, side: -0.363 },
    balls: { cue: [0.627,0.909], red1: [0.733,0.907], red2: [0.662,0.714], yellow: [1.312,0.767] },
  },
  {
    id: "s46",
    name: "Stage 46",
    covers: "softTouch",
    requires: "soft",
    par: 3,
    aimWindow: 4.75,
    solution: { deg: -56.262, speed: 1.171, tip: -0.074, side: 0 },
    balls: { cue: [1.889,0.865], red1: [2.007,0.623], red2: [2.386,0.395], yellow: [0.22,1.018] },
  },
  {
    id: "s47",
    name: "Stage 47",
    covers: "yellowBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4.5,
    solution: { deg: -118.877, speed: 1.4, tip: 0.212, side: -0.3 },
    balls: { cue: [0.8,1.005], red1: [0.669,0.694], red2: [0.25,0.326], yellow: [0.434,0.521] },
  },
  {
    id: "s48",
    name: "Stage 48",
    covers: "cushionBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4.5,
    solution: { deg: -121.296, speed: 1.992, tip: 0.375, side: 0 },
    balls: { cue: [1.908,1.102], red1: [1.684,0.673], red2: [0.191,0.225], yellow: [2.32,0.604] },
  },
  {
    id: "s49",
    name: "Stage 49",
    covers: "redsApart",
    requires: "any",
    par: 3,
    aimWindow: 4.5,
    solution: { deg: -61.71, speed: 3, tip: 0.19, side: 0.114 },
    balls: { cue: [0.434,0.852], red1: [0.592,0.492], red2: [2.242,0.21], yellow: [0.243,0.59] },
  },
  {
    id: "s50",
    name: "Stage 50",
    covers: "drawOnly",
    requires: "draw",
    par: 3,
    aimWindow: 4.5,
    solution: { deg: -169.536, speed: 1.71, tip: -0.4, side: 0 },
    balls: { cue: [1.064,0.555], red1: [0.872,0.504], red2: [1.023,0.671], yellow: [2.32,0.954] },
  },
  {
    id: "s51",
    name: "Stage 51",
    covers: "yellowTrap",
    requires: "any",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: -34.381, speed: 1.63, tip: 0.111, side: 0 },
    balls: { cue: [0.423,0.309], red1: [1.171,0.15], red2: [1.234,0.301], yellow: [0.797,0.23] },
  },
  {
    id: "s52",
    name: "Stage 52",
    covers: "yellowBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: -172.257, speed: 2.187, tip: 0.282, side: 0 },
    balls: { cue: [1.523,0.967], red1: [1.088,0.869], red2: [0.272,1.108], yellow: [0.72,0.99] },
  },
  {
    id: "s53",
    name: "Stage 53",
    covers: "englishOnly",
    requires: "english",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: -158.495, speed: 1.821, tip: 0.097, side: 0.394 },
    balls: { cue: [0.634,0.423], red1: [0.665,0.232], red2: [0.757,0.47], yellow: [0.822,0.511] },
  },
  {
    id: "s54",
    name: "Stage 54",
    covers: "yellowTrap",
    requires: "any",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 37.722, speed: 1.4, tip: 0.119, side: 0 },
    balls: { cue: [1.388,0.845], red1: [2.048,1.113], red2: [2.264,1.132], yellow: [1.718,0.979] },
  },
  {
    id: "s55",
    name: "Stage 55",
    covers: "yellowBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: -83.546, speed: 2.691, tip: 0.104, side: 0 },
    balls: { cue: [1.51,0.914], red1: [1.576,0.606], red2: [0.84,0.303], yellow: [1.185,0.458] },
  },
  {
    id: "s56",
    name: "Stage 56",
    covers: "englishOnly",
    requires: "english",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 89.622, speed: 2.379, tip: 0.297, side: -0.35 },
    balls: { cue: [1.065,0.852], red1: [1.133,0.909], red2: [1.303,0.82], yellow: [0.82,0.476] },
  },
  {
    id: "s57",
    name: "Stage 57",
    covers: "drawOnly",
    requires: "draw",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 65.78, speed: 1.4, tip: -0.346, side: 0 },
    balls: { cue: [2.129,0.631], red1: [2.192,0.798], red2: [2.209,0.571], yellow: [0.22,0.22] },
  },
  {
    id: "s58",
    name: "Stage 58",
    covers: "redsApart",
    requires: "any",
    par: 3,
    aimWindow: 4,
    solution: { deg: -9.715, speed: 2.365, tip: 0.234, side: 0.3 },
    balls: { cue: [0.519,0.884], red1: [0.934,0.853], red2: [2.232,0.187], yellow: [2.32,0.743] },
  },
  {
    id: "s59",
    name: "Stage 59",
    covers: "yellowBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 10.003, speed: 2.068, tip: 0.243, side: -0.3 },
    balls: { cue: [1.518,0.632], red1: [1.785,0.638], red2: [2.375,0.978], yellow: [2.052,0.828] },
  },
  {
    id: "s60",
    name: "Stage 60",
    covers: "englishOnly",
    requires: "english",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 178.865, speed: 2.164, tip: -0.12, side: -0.441 },
    balls: { cue: [0.597,0.89], red1: [0.269,0.98], red2: [0.528,1.172], yellow: [0.22,0.377] },
  },
  {
    id: "s61",
    name: "Stage 61",
    covers: "drawOnly",
    requires: "draw",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 147.909, speed: 1.319, tip: -0.341, side: 0 },
    balls: { cue: [1.7,0.453], red1: [1.562,0.528], red2: [1.827,0.504], yellow: [2.262,0.22] },
  },
  {
    id: "s62",
    name: "Stage 62",
    covers: "railFirst",
    requires: "cushionFirst",
    par: 3,
    aimWindow: 4.25,
    solution: { deg: 160.748, speed: 2.533, tip: 0.151, side: 0 },
    balls: { cue: [0.411,0.396], red1: [0.308,0.578], red2: [0.396,0.741], yellow: [0.359,0.487] },
  },
  {
    id: "s63",
    name: "Stage 63",
    covers: "redsApart",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: -59.139, speed: 1.937, tip: 0, side: 0 },
    balls: { cue: [0.897,0.711], red1: [1.081,0.326], red2: [2.255,0.172], yellow: [0.22,0.704] },
  },
  {
    id: "s64",
    name: "Stage 64",
    covers: "yellowTrap",
    requires: "any",
    par: 3,
    aimWindow: 4,
    solution: { deg: 121.964, speed: 2.282, tip: 0, side: 0 },
    balls: { cue: [0.506,1.108], red1: [0.093,0.409], red2: [0.114,0.055], yellow: [0.3,0.759] },
  },
  {
    id: "s65",
    name: "Stage 65",
    covers: "cushionBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4,
    solution: { deg: 81.626, speed: 2.763, tip: 0.06, side: -0.3 },
    balls: { cue: [1.756,0.606], red1: [1.832,0.916], red2: [1.369,1.091], yellow: [0.575,1.05] },
  },
  {
    id: "s66",
    name: "Stage 66",
    covers: "drawOnly",
    requires: "draw",
    par: 3,
    aimWindow: 4,
    solution: { deg: 111.163, speed: 1.507, tip: -0.4, side: 0 },
    balls: { cue: [0.504,0.377], red1: [0.452,0.521], red2: [0.53,0.182], yellow: [2.32,0.22] },
  },
  {
    id: "s67",
    name: "Stage 67",
    covers: "cushionBetween",
    requires: "someCushion",
    par: 3,
    aimWindow: 4,
    solution: { deg: 106.778, speed: 2.855, tip: 0.199, side: 0 },
    balls: { cue: [2.319,0.697], red1: [2.23,1.107], red2: [1.585,1.03], yellow: [1.074,0.678] },
  },
  {
    id: "s68",
    name: "Stage 68",
    covers: "railFirst",
    requires: "cushionFirst",
    par: 3,
    aimWindow: 4,
    solution: { deg: 73.579, speed: 2.732, tip: 0.359, side: 0 },
    balls: { cue: [0.869,0.819], red1: [1.046,0.866], red2: [1.222,0.793], yellow: [0.957,0.843] },
  },
  {
    id: "s69",
    name: "Stage 69",
    covers: "cushionBetween",
    requires: "someCushion",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 27.846, speed: 2.374, tip: 0.385, side: -0.3 },
    balls: { cue: [1.081,1.074], red1: [1.474,1.166], red2: [2.346,0.928], yellow: [2.201,0.667] },
  },
  {
    id: "s70",
    name: "Stage 70",
    covers: "yellowTrap",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 161.183, speed: 3.414, tip: 0.4, side: -0.3 },
    balls: { cue: [2.168,1.07], red1: [1.317,1.13], red2: [1.15,1.174], yellow: [1.742,1.1] },
  },
  {
    id: "s71",
    name: "Stage 71",
    covers: "drawOnly",
    requires: "draw",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 53.574, speed: 1.4, tip: -0.415, side: 0.3 },
    balls: { cue: [1.632,0.76], red1: [1.73,0.9], red2: [1.58,0.677], yellow: [0.303,0.227] },
  },
  {
    id: "s72",
    name: "Stage 72",
    covers: "thinBoth",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 102.145, speed: 2.719, tip: 0.118, side: 0 },
    balls: { cue: [2.054,0.375], red1: [1.938,0.656], red2: [2.008,0.787], yellow: [1.157,0.596] },
  },
  {
    id: "s73",
    name: "Stage 73",
    covers: "railFirst",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 119.254, speed: 2.41, tip: 0.202, side: 0 },
    balls: { cue: [1.282,0.887], red1: [0.966,0.913], red2: [0.73,0.825], yellow: [1.124,0.9] },
  },
  {
    id: "s74",
    name: "Stage 74",
    covers: "longRange",
    requires: "any",
    par: 4,
    aimWindow: 3.5,
    solution: { deg: 13.965, speed: 2.791, tip: 0.221, side: 0 },
    balls: { cue: [0.481,1.09], red1: [2.297,1.024], red2: [2.168,1.17], yellow: [2.144,0.854] },
  },
  {
    id: "s75",
    name: "Stage 75",
    covers: "thinBoth",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 121.571, speed: 1.76, tip: -0.083, side: 0 },
    balls: { cue: [1.58,0.448], red1: [1.4,0.637], red2: [1.439,0.971], yellow: [2.173,0.761] },
  },
  {
    id: "s76",
    name: "Stage 76",
    covers: "yellowTrap",
    requires: "any",
    par: 4,
    aimWindow: 3.5,
    solution: { deg: 28.078, speed: 1.847, tip: 0.254, side: 0 },
    balls: { cue: [1.298,0.955], red1: [2.254,1.128], red2: [2.43,0.819], yellow: [1.776,1.042] },
  },
  {
    id: "s77",
    name: "Stage 77",
    covers: "railFirst",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3.5,
    solution: { deg: -43.163, speed: 2.98, tip: 0.329, side: 0.3 },
    balls: { cue: [2.398,1.074], red1: [2.168,0.755], red2: [2.15,0.529], yellow: [2.283,0.915] },
  },
  {
    id: "s78",
    name: "Stage 78",
    covers: "twoCushion",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3,
    solution: { deg: 8.981, speed: 2.689, tip: 0.05, side: 0.331 },
    balls: { cue: [2.285,1.035], red1: [1.206,0.989], red2: [1.095,0.792], yellow: [1.746,1.012] },
  },
  {
    id: "s79",
    name: "Stage 79",
    covers: "thinBoth",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: -113.81, speed: 2.359, tip: 0.095, side: 0 },
    balls: { cue: [0.422,0.997], red1: [0.229,0.695], red2: [0.274,0.456], yellow: [1.868,0.22] },
  },
  {
    id: "s80",
    name: "Stage 80",
    covers: "twoCushion",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3.5,
    solution: { deg: 37.885, speed: 3.085, tip: 0.029, side: 0.282 },
    balls: { cue: [2.226,0.585], red1: [1.672,0.988], red2: [1.663,0.84], yellow: [1.949,0.787] },
  },
  {
    id: "s81",
    name: "Stage 81",
    covers: "railFirst",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3.25,
    solution: { deg: 21.917, speed: 2.246, tip: -0.4, side: 0.3 },
    balls: { cue: [1.78,0.676], red1: [1.706,0.954], red2: [1.545,1.029], yellow: [1.743,0.815] },
  },
  {
    id: "s82",
    name: "Stage 82",
    covers: "thinBoth",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: -114.306, speed: 2.593, tip: 0.168, side: 0 },
    balls: { cue: [1.773,0.632], red1: [1.698,0.332], red2: [1.558,0.264], yellow: [1.953,0.679] },
  },
  {
    id: "s83",
    name: "Stage 83",
    covers: "longThin",
    requires: "any",
    par: 4,
    aimWindow: 2.75,
    solution: { deg: 8.276, speed: 3.66, tip: 0.196, side: 0 },
    balls: { cue: [0.256,0.819], red1: [1.364,0.946], red2: [1.577,1.162], yellow: [1.106,0.4] },
  },
  {
    id: "s84",
    name: "Stage 84",
    covers: "sideRail",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3.25,
    solution: { deg: -66.843, speed: 2.866, tip: 0.328, side: 0.3 },
    balls: { cue: [0.724,0.302], red1: [0.993,0.35], red2: [1.232,0.304], yellow: [0.858,0.326] },
  },
  {
    id: "s85",
    name: "Stage 85",
    covers: "thinBoth",
    requires: "any",
    par: 4,
    aimWindow: 3.75,
    solution: { deg: 29.118, speed: 1.902, tip: 0.27, side: 0 },
    balls: { cue: [0.935,0.899], red1: [1.16,1.08], red2: [1.395,0.977], yellow: [1.299,0.925] },
  },
  {
    id: "s86",
    name: "Stage 86",
    covers: "sideRail",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 3,
    solution: { deg: -118.034, speed: 3.352, tip: 0.228, side: -0.442 },
    balls: { cue: [0.548,0.359], red1: [0.3,0.713], red2: [0.206,0.959], yellow: [0.424,0.536] },
  },
  {
    id: "s87",
    name: "Stage 87",
    covers: "spread",
    requires: "any",
    par: 4,
    aimWindow: 2.5,
    solution: { deg: 89.397, speed: 3.206, tip: 0.062, side: 0.012 },
    balls: { cue: [0.618,0.345], red1: [0.655,0.901], red2: [0.176,0.781], yellow: [1.862,0.22] },
  },
  {
    id: "s88",
    name: "Stage 88",
    covers: "longThin",
    requires: "any",
    par: 4,
    aimWindow: 2.5,
    solution: { deg: 2.853, speed: 3.294, tip: 0.308, side: 0 },
    balls: { cue: [0.695,0.351], red1: [1.93,0.447], red2: [2.223,0.202], yellow: [0.922,0.645] },
  },
  {
    id: "s89",
    name: "Stage 89",
    covers: "sideRail",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 2.75,
    solution: { deg: 122.045, speed: 2.582, tip: 0.088, side: 0.454 },
    balls: { cue: [1.078,0.569], red1: [0.407,0.974], red2: [0.178,1.024], yellow: [0.743,0.771] },
  },
  {
    id: "s90",
    name: "Stage 90",
    covers: "longThin",
    requires: "any",
    par: 4,
    aimWindow: 2.75,
    solution: { deg: 51.109, speed: 2.694, tip: 0.074, side: 0 },
    balls: { cue: [0.541,0.987], red1: [1.442,0.326], red2: [1.391,0.209], yellow: [0.22,0.322] },
  },
  {
    id: "s91",
    name: "Stage 91",
    covers: "twoCushion",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 2.25,
    solution: { deg: -144.769, speed: 2.791, tip: 0.029, side: -0.151 },
    balls: { cue: [1.356,0.797], red1: [0.29,0.49], red2: [0.456,0.471], yellow: [0.823,0.644] },
  },
  {
    id: "s92",
    name: "Stage 92",
    covers: "sideRail",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 2.75,
    solution: { deg: 47.728, speed: 3.332, tip: 0.244, side: -0.449 },
    balls: { cue: [1.223,0.656], red1: [2.039,0.965], red2: [2.215,1.054], yellow: [1.631,0.81] },
  },
  {
    id: "s93",
    name: "Stage 93",
    covers: "longRange",
    requires: "any",
    par: 4,
    aimWindow: 2.25,
    solution: { deg: -22.899, speed: 1.4, tip: 0.291, side: 0 },
    balls: { cue: [0.372,0.404], red1: [1.94,0.229], red2: [2.117,0.1], yellow: [0.22,0.516] },
  },
  {
    id: "s94",
    name: "Stage 94",
    covers: "twoCushion",
    requires: "cushionFirst",
    par: 4,
    aimWindow: 2,
    solution: { deg: -147.493, speed: 2.2, tip: 0.184, side: 0 },
    balls: { cue: [0.684,0.618], red1: [0.957,0.324], red2: [1.281,0.231], yellow: [0.821,0.471] },
  },
  {
    id: "s95",
    name: "Stage 95",
    covers: "longThin",
    requires: "any",
    par: 4,
    aimWindow: 2,
    solution: { deg: 6.625, speed: 2.617, tip: 0.079, side: 0 },
    balls: { cue: [0.491,0.897], red1: [2.305,1.065], red2: [2.452,1.161], yellow: [1.895,0.749] },
  },
  {
    id: "s96",
    name: "Stage 96",
    covers: "longRange",
    requires: "any",
    par: 4,
    aimWindow: 2.25,
    solution: { deg: 7.114, speed: 3.091, tip: 0.224, side: 0 },
    balls: { cue: [0.552,0.814], red1: [1.833,1.01], red2: [2.023,0.818], yellow: [1.309,0.22] },
  },
  {
    id: "s97",
    name: "Stage 97",
    covers: "spread",
    requires: "any",
    par: 4,
    aimWindow: 1.75,
    solution: { deg: -55.435, speed: 3.171, tip: 0.385, side: 0.27 },
    balls: { cue: [0.384,0.436], red1: [1.185,0.603], red2: [1.167,1.072], yellow: [0.533,1.05] },
  },
  {
    id: "s98",
    name: "Stage 98",
    covers: "longRange",
    requires: "any",
    par: 4,
    aimWindow: 2,
    solution: { deg: 27.33, speed: 2.597, tip: 0.092, side: 0 },
    balls: { cue: [0.574,0.802], red1: [2.041,1.056], red2: [2.188,0.809], yellow: [1.603,1.05] },
  },
  {
    id: "s99",
    name: "Stage 99",
    covers: "spread",
    requires: "any",
    par: 4,
    aimWindow: 1.5,
    solution: { deg: 3.828, speed: 1.4, tip: 0.177, side: -0.028 },
    balls: { cue: [0.537,0.874], red1: [1.631,0.9], red2: [2.329,1.088], yellow: [1.921,0.22] },
  },
  {
    id: "s100",
    name: "Stage 100",
    covers: "spread",
    requires: "any",
    par: 4,
    aimWindow: 1.5,
    solution: { deg: 171.688, speed: 2.763, tip: 0.024, side: 0.262 },
    balls: { cue: [0.421,0.407], red1: [1.212,0.243], red2: [2.309,0.756], yellow: [0.22,1.05] },
  },
];

/**
 * The standard four-ball opening, for free play.
 * Korean rules place the shooter's cue ball beside one red and start the
 * game by playing the red at the far end.
 * https://en.wikipedia.org/wiki/Four-ball_billiards
 */
export const OPENING = {
  // Offsets as FRACTIONS of the table, not centimetres. They were tuned
  // on a 2.84m table and a table is the only unit that keeps an opening
  // looking like the same opening when the table changes size.
  cue: [L / 4, W / 2 - 0.113 * W],
  red1: [L / 4, W / 2 + 0.099 * W],
  red2: [(3 * L) / 4, W / 2],
  yellow: [L / 4 - 0.106 * L, W / 2 + 0.211 * W],
};

/** Stage placement -> the ball list physics.createWorld() wants. */
export function ballsFrom(placement) {
  return [
    { id: "cue", x: placement.cue[0], y: placement.cue[1], color: "white" },
    { id: "yellow", x: placement.yellow[0], y: placement.yellow[1], color: "yellow" },
    { id: "red1", x: placement.red1[0], y: placement.red1[1], color: "red" },
    { id: "red2", x: placement.red2[0], y: placement.red2[1], color: "red" },
  ];
}

/**
 * Par at a difficulty. Level 0 asks for one point, 1 for two, 2 for three.
 *
 * The multiplier is the honest part: two points is two problems, so it
 * costs about twice the strokes. The +1 and +2 are not padding — every
 * stage's OWN position was built backwards from a shot that works and is
 * measured (`aimWindow`), and none of the positions a run leaves behind
 * were. tools/chain-check.mjs proves a scoring line exists from there;
 * it does not promise the line is as forgiving as the designed one. So
 * each leg past the first is allowed one extra stroke to find it, which
 * is what keeps three stars possible on a stage whose second leg happens
 * to be tight rather than merely on the ones that deal kindly.
 */
export function parFor(stage, level = 0) {
  return stage.par * (level + 1) + level;
}

/** Stars for clearing a stage in `shots` strokes. Par is the shot this
 * stage teaches, played right — which is why par tracks aimWindow: a
 * stage that forgives two degrees is not a one-attempt stage. */
export function starsFor(stage, shots, level = 0) {
  const par = parFor(stage, level);
  if (shots <= par) return 3;
  if (shots <= par + 2) return 2;
  return 1;
}
